data_dir: /workspace7/torchmd-AD/train_val_short
train_set: train_short.txt
val_set: val_short.txt
prot_save: 3SWY_A
train_dir: training/train_13_08_dihedrals_short
device: cpu
metro: 01
par_mod: uniform
forcefield: /shared/carles/torchMD-DMS/parameters/ca_priors-angles_general.yaml
forceterms: bonds repulsioncg angles dihedrals
n_epochs: 50
max_steps: 250
lr: 0.0001
verbose: True
