name: torchmd-exp
channels:
  - raimis
  - mmh
  - conda-forge
  - acellera
  - bioconda
dependencies:
  - ase
  - h5py
  - matplotlib
  # An official NNPOps packages still not available
  - mmh::nnpops==0.2
  - pip
  - python==3.9
  - pytorch==1.10.0
  - moleculekit
  - raimis/label/rc::openmm-torch==0.7rc2
  # The official PyTorch Geometric package is not compatible with conda-forge,
  # while the package on conda-forge is broken
  # (https://github.com/pyg-team/pytorch_geometric/issues/3660).
  # Until a better solution is found a have custom package to plug the gap.
  - raimis::pytorch-geometric==2.0.2
  - pytorch-lightning==1.3.8
  - setuptools==59.5.0 # Pin due to https://github.com/pytorch/pytorch/pull/69904
  - tqdm
  # Dev tools
  - flake8
  - pytest

