data_dir: /workspace7/torchmd-AD/train_val_torchmd
train_set: train.txt
val_set: val.txt
prot_save: 3SWY_A
train_dir: training/train_12_08_angles_250steps
device: cpu
metro: 01
par_mod: uniform
forceterms: bonds repulsioncg angles
n_epochs: 50
max_steps: 250
lr: 0.001
verbose: True
