data_dir: /workspace7/torchmd-AD/train_val_torchmd
prot_save: 3SWY_A
train_dir: training/train_terms
device: cuda:1
metro: 17
par_mod: uniform 
forceterms: bonds repulsioncg angles
n_epochs: 50
max_steps: 2000
lr: 0.001
verbose: True
