activation: tanh
atom_filter: -1
batch_size: 1
ubatch_size: 1
cutoff_lower: 3.0
cutoff_upper: 12.0
cutoff: 9
reference_dir: '/workspace7/torchmd-AD/claudi_64_proteins'
levels_dir: '/workspace7/torchmd-AD/claudi_64_proteins'
derivative: True
device: 'cuda:0'
embedding_dimension: 128
exclusions: ('bonds')
forcefield: '/shared/carles/repo/torchmd-exp/data/ca_priors-dihedrals_general.yaml'
forceterms: 
    - bonds
    - repulsioncg 
    - dihedrals
last_sn: False
lr: 5.e-5
log_dir: 'train_64_claudi'
max_steps: 400
output_period: 10
max_num_neighbors: 128
max_z: 100
neighbor_embedding: False
neff: 0.9
ngpus: -1
num_filters: 256
num_layers: 4
num_nodes: 1
num_rbf: 18
reduce_op: add
precision: 32
rbf_type: expnorm
replicas: 1
seed: 200
train_set: claudi_64_proteins.txt
trainable_rbf: True
timestep: 5